# frozen_string_literal: true

Ocean.destroy_all

Ocean.create name: 'Atlantic Ocean', description: 'Atlantic Ocean, body of salt water covering approximately one-fifth of Earth’s surface and separating the continents of Europe and Africa to the east from those of North and South America to the west. The ocean’s name, derived from Greek mythology, means the “Sea of Atlas.” It is second in size only to the Pacific Ocean.'
Ocean.create name: 'Arctic Ocean', description: 'Arctic Ocean, smallest of the world’s oceans, centring approximately on the North Pole. The Arctic Ocean and its marginal seas—the Chukchi, East Siberian, Laptev, Kara, Barents, White, Greenland, and Beaufort and, according to some oceanographers, also the Bering and Norwegian seas—are the least-known basins and bodies of water in the world ocean as a result of their remoteness, hostile weather, and perennial or seasonal ice cover. This is changing, however, because the Arctic may exhibit a strong response to global change and may be capable of initiating dramatic climatic changes through alterations induced in the oceanic thermohaline circulation by its cold, southward-moving currents or through its effects on the global albedo resulting from changes in its total ice cover.'
Ocean.create name: 'Indian Ocean', description: 'Indian Ocean, body of salt water covering approximately one-fifth of the total ocean area of the world. It is the smallest, geologically youngest, and physically most complex of the world’s three major oceans. It stretches for more than 6,200 miles (10,000 km) between the southern tips of Africa and Australia and, without its marginal seas, has an area of about 28,360,000 square miles (73,440,000 square km). The Indian Ocean’s average depth is 12,990 feet (3,960 metres), and its deepest point, in the Sunda Deep of the Java Trench off the southern coast of the island of Java (Indonesia), is 24,442 feet (7,450 metres).'
Ocean.create name: 'Pacific Ocean', description: 'Pacific Ocean, body of salt water extending from the Antarctic region in the south to the Arctic in the north and lying between the continents of Asia and Australia on the west and North and South America on the east.'
Ocean.create name: 'Southern Ocean', description: 'Southern Ocean, also called Antarctic Ocean, the southern portions of the Pacific, Atlantic, and Indian oceans and their tributary seas surrounding Antarctica. Unbroken by any other continental landmass, the Southern Ocean’s narrowest constriction is the Drake Passage, 600 miles (about 1,000 km) wide, between South America and the tip of the Antarctic Peninsula.'
